sk2-malkong/Frontend

package-lock.json, package.json, src/pages/mypage/MyPage.jsx, src/pages/mypage/MyPageContainer.js, src/pages/mypage/style.js, src/routes/router.js, yarn.lock
=> 마이 페이지 연결 설정

.gitignore, src/pages/limitationlog/LimitationLog.jsx, src/pages/limitationlog/LimitationLogContainer.js, src/pages/limitationlog/downarrrow_btn.svg, src/pages/limitationlog/style.js, src/pages/limitationlog/uparrow_btn.svg, src/routes/router.js
=> 이용제한내역 페이지 제작중, 이용제한내역 라우터 추가

src/pages/postcreate/PostCreate.jsx, src/pages/postcreate/PostCreateContainer.js, src/pages/postcreate/PostEdit.jsx, src/pages/postcreate/PostEditContainer.js, src/pages/postcreate/PostForm.jsx, src/pages/postcreate/style.js, src/pages/postdetail/CommentInput.jsx, src/pages/postdetail/CommentList.jsx, src/pages/postdetail/PostDetail.jsx, src/pages/postdetail/PostDetailContainer.js, src/pages/postdetail/style.js
=> 이용 제한 기능 추가

src/pages/postcreate/PostCreate.jsx, src/pages/postcreate/PostEdit.jsx, src/pages/postcreate/PostEditContainer.js, src/pages/postdetail/CommentInput.jsx, src/pages/postdetail/CommentList.jsx, src/pages/postdetail/PostDetail.jsx, src/pages/postdetail/style.js, yarn.lock
=> post api 연동 수정

src/pages/postcreate/PostCreate.jsx, src/pages/postcreate/PostCreateContainer.js, src/pages/postcreate/PostEdit.jsx, src/pages/postcreate/PostEditContainer.js, src/pages/postcreate/PostForm.jsx, src/pages/postcreate/PostFormContainer.js, src/pages/postcreate/style.js, src/pages/postdetail/CommentInput.jsx, src/pages/postdetail/CommentList.jsx, src/pages/postdetail/PostDetail.jsx, src/pages/postdetail/PostDetailContainer.js, src/pages/postdetail/style.js
postcreate/postdetail 주석 수정 및 파일 통일성을 위한 코드 수정
=> postcreate/postdetail 주석 수정 및 파일 통일성을 위한 코드 수정

src/pages/api/comment.js, src/pages/api/postcreate.js, src/pages/api/postdetail.js, src/pages/api/postedit.js, src/pages/postcreate/PostCreate.jsx, src/pages/postcreate/PostEdit.jsx, src/pages/postdetail/CommentInput.jsx, src/pages/postdetail/CommentList.jsx, src/pages/postdetail/PostDetail.jsx, src/pages/postdetail/PostDetailContainer.js
=> postcreate/postdetail api 분리

src/pages/postdetail/PostDetail.jsx
=> 욕설 제한 5회마다로 변경

src/pages/mypage/MyPage.jsx
=> 마이 페이지 페이지 연동

src/pages/api/userApi.js, src/pages/mypage/MyPage.jsx, src/pages/mypage/MyPageContainer.js, src/pages/profileFix/ProfileFix.jsx, src/pages/profileFix/ProfileFixContainer.js
Fix: 마이페이지, 프로필 수정 페이지 디지인 페턴 적용
=> Fix: 마이페이지, 프로필 수정 페이지 디지인 페턴 적용

src/pages/api/auth.ts, src/pages/api/comment.ts, src/pages/postcreate/PostCreate.tsx, src/pages/postcreate/PostEdit.tsx, src/pages/postcreate/PostForm.tsx, src/pages/postcreate/PostFormContainer.tsx, src/pages/postdetail/CommentInput.tsx, src/pages/postdetail/CommentList.tsx, src/pages/postdetail/PostDetail.tsx
postcreate/postdetail 이용 제한 기능 추가
=> postcreate/postdetail 이용 제한 기능 추가

src/pages/postcreate/PostCreate.tsx, src/pages/postcreate/PostForm.tsx, src/pages/postcreate/PostFormContainer.tsx, src/pages/postdetail/CommentInput.tsx, src/pages/postdetail/PostDetail.tsx
postdetail/postcreate 이용 제한 기능 다른 로컬에서 안되는 거 수정
=> postdetail/postcreate 이용 제한 기능 다른 로컬에서 안되는 거 수정

src/routes/router.tsx
=> Router fix

src/pages/layout/index/_component/Header/Header.tsx, src/pages/layout/index/apiIntroMain/PdMain.tsx, src/pages/layout/index/docspages/DocsLayout.tsx, src/pages/layout/index/docspages/DocsStyle.ts
메인-문서 페이지 연결/문서 페이지 헤더 추가/헤더 기능 수정
=>  메인-문서 페이지 연결/문서 페이지 헤더 추가/헤더 기능 수정

src/App.tsx, src/index.tsx, src/pages/PurgoChat/Mockup/IPhoneMockup.js, src/pages/PurgoChat/Mockup/iPhone.svg, src/pages/PurgoChat/components/NicknameForm.js, src/pages/PurgoChat/context/NicknameContext.js, src/pages/PurgoChat/pages/ChatRoomPage.js, src/pages/PurgoChat/pages/NicknamePage.js, src/pages/mypage/MyPage.tsx, src/pages/mypage/MyPageContainer.tsx, src/routes/router.tsx
=> Feat: 라우터 수정, chat페이지 연결

package-lock.json, src/pages/layout/index/_component/ApiKeyPopup.tsx
=> Fix: api 발급 주소 변경

src/pages/layout/index/_component/ApiKeyPopup.tsx
=> Fix: api 키 복사

src/pages/api/auth.ts
=>  Fix: api 키 복사

src/pages/api/auth.ts
=> 회원가입 api 수정2

src/pages/layout/index/docspages/components/CopyButton.tsx
=> api 소개 문서 페이지 복사붙여넣기 버튼 수정

src/pages/api/axios.ts, src/pages/layout/Layout.tsx, src/pages/limitationlog/LimitationLogContainer.tsx, src/pages/limitationlog/style.ts
Fix: 이용제한 내역 없음 텍스트 추가, 로그아웃 누르면 메인 페이지 이동
=> Fix: 이용제한 내역 없음 텍스트 추가, 로그아웃 누르면 메인 페이지 이동

src/pages/api/postlist.ts, src/pages/mypage/MyPage.tsx, src/pages/mypage/MyPageContainer.tsx, src/pages/mypage/style.ts, src/pages/mypostlist/MyPostList.tsx, src/pages/mypostlist/MyPostListContainer.tsx, src/pages/mypostlist/style.ts, src/pages/search/style.ts, src/routes/router.tsx
내가 작성한 글 리스트/검색된 글 리스트 기능 추가/수정
=> 내가 작성한 글 리스트/검색된 글 리스트 기능 추가/수정

src/pages/api/auth.ts, src/pages/api/axios.ts, src/pages/api/userApi.ts
=> Fix: refreshToken 자동 연결

src/pages/layout/Layout.tsx
=> http에서 종료시 로그 아웃

src/pages/postdetail/CommentInput.tsx, src/pages/postdetail/PostDetail.tsx
=> 비회원 정보 403 에러 수정

src/pages/layout/Layout.tsx
=> Fix: http종료시 자동 로그아웃세로고침제거

src/modules/user.js, src/pages/api/axios.ts, src/pages/postcreate/PostEdit.tsx
=> Fix: 메인 베너 수정
